# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DangNhap.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DangNhap(object):
    def setupUi(self, DangNhap):
        DangNhap.setObjectName("DangNhap")
        DangNhap.resize(1003, 653)
        DangNhap.setMinimumSize(QtCore.QSize(1003, 653))
        DangNhap.setMaximumSize(QtCore.QSize(1003, 653))
        self.centralwidget = QtWidgets.QWidget(DangNhap)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(620, 10, 351, 601))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.136364 rgba(255, 140, 0, 255), stop:0.909091 rgba(255, 173, 0, 255))")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(-20, 30, 381, 151))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(-10, 200, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(0, 330, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.txt_tk = QtWidgets.QLineEdit(self.frame)
        self.txt_tk.setGeometry(QtCore.QRect(60, 270, 241, 31))
        self.txt_tk.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(10,10, 10);")
        self.txt_tk.setObjectName("txt_tk")
        self.txt_mk = QtWidgets.QLineEdit(self.frame)
        self.txt_mk.setGeometry(QtCore.QRect(60, 400, 241, 31))
        self.txt_mk.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.txt_mk.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(10,10, 10);")
        self.txt_mk.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_mk.setObjectName("txt_mk")
        self.p_dn = QtWidgets.QPushButton(self.frame)
        self.p_dn.setGeometry(QtCore.QRect(90, 470, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.p_dn.setFont(font)
        self.p_dn.setStyleSheet("QPushButton#p_dn{\n"
"    color: rgb(10, 80, 255);\n"
"    background-color: rgb(0, 232, 232);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton#p_dn:hover{\n"
"    background-color: rgb(248, 165, 0);\n"
"}\n"
"QPushButton#p_dn:pressed {\n"
"\n"
"    background-color: rgb(255, 139, 38);\n"
"}")
        self.p_dn.setObjectName("p_dn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1011, 651))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/hinhanh/Hinhanh/Thuvien.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label.raise_()
        self.frame.raise_()
        DangNhap.setCentralWidget(self.centralwidget)

        self.retranslateUi(DangNhap)
        QtCore.QMetaObject.connectSlotsByName(DangNhap)

    def retranslateUi(self, DangNhap):
        _translate = QtCore.QCoreApplication.translate
        DangNhap.setWindowTitle(_translate("DangNhap", "MainWindow"))
        self.label_4.setText(_translate("DangNhap", "LOGIN"))
        self.label_5.setText(_translate("DangNhap", "           Tài khoản"))
        self.label_6.setText(_translate("DangNhap", "          Mật khẩu"))
        self.p_dn.setText(_translate("DangNhap", "ĐĂNG NHẬP"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DangNhap = QtWidgets.QMainWindow()
    ui = Ui_DangNhap()
    ui.setupUi(DangNhap)
    DangNhap.show()
    sys.exit(app.exec_())
