# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'thongke.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Thongke(object):
    def setupUi(self, Thongke):
        Thongke.setObjectName("Thongke")
        Thongke.resize(931, 699)
        self.centralwidget = QtWidgets.QWidget(Thongke)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, -10, 941, 201))
        self.label.setStyleSheet("background-color: rgb(40, 109, 87);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(490, 0, 431, 191))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("HinhAnh/background-trangchu1-removebg-preview.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.p_trolai = QtWidgets.QPushButton(self.centralwidget)
        self.p_trolai.setGeometry(QtCore.QRect(10, 130, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p_trolai.setFont(font)
        self.p_trolai.setStyleSheet("QPushButton#p_trolai{\n"
"background-color: qlineargradient(spread:pad, x1:0.0199005, y1:0.204, x2:0.726, y2:0.7105, stop:0.19403 rgba(63, 183, 186, 255), stop:0.900498 rgba(115, 214, 139, 255));\n"
"border-radius: 15px;\n"
"}\n"
"QPushButton#p_trolai::hover{\n"
"    background-color:rgb(255, 170, 0);\n"
"}\n"
"")
        self.p_trolai.setObjectName("p_trolai")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 190, 941, 511))
        self.widget.setStyleSheet("background-color: rgb(226, 234, 221);")
        self.widget.setObjectName("widget")
        self.tb_tk = QtWidgets.QTableWidget(self.widget)
        self.tb_tk.setGeometry(QtCore.QRect(310, 20, 581, 451))
        self.tb_tk.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tb_tk.setTabKeyNavigation(False)
        self.tb_tk.setProperty("showDropIndicator", False)
        self.tb_tk.setDragDropOverwriteMode(False)
        self.tb_tk.setAlternatingRowColors(True)
        self.tb_tk.setObjectName("tb_tk")
        self.tb_tk.setColumnCount(0)
        self.tb_tk.setRowCount(0)
        self.tb_tk.horizontalHeader().setDefaultSectionSize(166)
        self.tb_tk.horizontalHeader().setStretchLastSection(True)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(290, 10, 621, 481))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 30px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.p_thongke = QtWidgets.QPushButton(self.widget)
        self.p_thongke.setGeometry(QtCore.QRect(20, 370, 221, 41))
        self.p_thongke.setStyleSheet("background-color: rgb(0, 207, 207);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.p_thongke.setObjectName("p_thongke")
        self.p_excel = QtWidgets.QPushButton(self.widget)
        self.p_excel.setGeometry(QtCore.QRect(20, 430, 221, 41))
        self.p_excel.setStyleSheet("background-color: rgb(0, 207, 207);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.p_excel.setObjectName("p_excel")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(30, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(30, 100, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.Ngaymuon = QtWidgets.QDateEdit(self.widget)
        self.Ngaymuon.setGeometry(QtCore.QRect(120, 40, 110, 22))
        self.Ngaymuon.setObjectName("Ngaymuon")
        self.Ngaytra = QtWidgets.QDateEdit(self.widget)
        self.Ngaytra.setGeometry(QtCore.QRect(120, 100, 110, 22))
        self.Ngaytra.setObjectName("Ngaytra")
        self.label_2.raise_()
        self.tb_tk.raise_()
        self.p_thongke.raise_()
        self.p_excel.raise_()
        self.label_5.raise_()
        self.label_8.raise_()
        self.Ngaymuon.raise_()
        self.Ngaytra.raise_()
        self.p_dx = QtWidgets.QPushButton(self.centralwidget)
        self.p_dx.setGeometry(QtCore.QRect(170, 130, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p_dx.setFont(font)
        self.p_dx.setStyleSheet("QPushButton#p_dx{\n"
"background-color: qlineargradient(spread:pad, x1:0.0199005, y1:0.204, x2:0.726, y2:0.7105, stop:0.19403 rgba(63, 183, 186, 255), stop:0.900498 rgba(115, 214, 139, 255));\n"
"border-radius: 15px;\n"
"}\n"
"QPushButton#p_dx::hover{\n"
"    background-color:rgb(255, 170, 0);\n"
"}\n"
"")
        self.p_dx.setObjectName("p_dx")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(-50, 30, 891, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color:rgb(255, 255, 255),\n"
"")
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(730, 20, 201, 161))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("Hinhanh/logo1.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.widget.raise_()
        self.label.raise_()
        self.label_9.raise_()
        self.p_trolai.raise_()
        self.p_dx.raise_()
        self.label_15.raise_()
        self.label_14.raise_()
        Thongke.setCentralWidget(self.centralwidget)

        self.retranslateUi(Thongke)
        QtCore.QMetaObject.connectSlotsByName(Thongke)

    def retranslateUi(self, Thongke):
        _translate = QtCore.QCoreApplication.translate
        Thongke.setWindowTitle(_translate("Thongke", "MainWindow"))
        self.p_trolai.setText(_translate("Thongke", "Trở lại"))
        self.p_thongke.setText(_translate("Thongke", "Thống kê"))
        self.p_excel.setText(_translate("Thongke", "Xuất Excel"))
        self.label_5.setText(_translate("Thongke", "Ngày mượn"))
        self.label_8.setText(_translate("Thongke", "Ngày trả"))
        self.p_dx.setText(_translate("Thongke", "Đăng xuất"))
        self.label_15.setText(_translate("Thongke", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600;\">HỆ THỐNG THƯ VIỆN SÁCH ĐIỆN TỬ</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Thongke = QtWidgets.QMainWindow()
    ui = Ui_Thongke()
    ui.setupUi(Thongke)
    Thongke.show()
    sys.exit(app.exec_())
