# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Trangchu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Trangchu(object):
    def setupUi(self, Trangchu):
        Trangchu.setObjectName("Trangchu")
        Trangchu.resize(1149, 970)
        self.centralwidget = QtWidgets.QWidget(Trangchu)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(-10, 0, 1161, 971))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setGeometry(QtCore.QRect(10, -20, 1431, 211))
        self.frame.setMaximumSize(QtCore.QSize(16777100, 16777000))
        self.frame.setStyleSheet("background-color: rgb(40, 109, 87);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.p_trangchu = QtWidgets.QPushButton(self.frame)
        self.p_trangchu.setGeometry(QtCore.QRect(40, 140, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.p_trangchu.setFont(font)
        self.p_trangchu.setAutoFillBackground(False)
        self.p_trangchu.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.0199005, y1:0.204, x2:0.726, y2:0.7105, stop:0.19403 rgba(50, 148, 150, 255), stop:0.900498 rgba(81, 152, 98, 255));\n"
"color: rgb(255, 255, 255);\n"
"border-radius:15px ;")
        self.p_trangchu.setObjectName("p_trangchu")
        self.p_quanly = QtWidgets.QPushButton(self.frame)
        self.p_quanly.setGeometry(QtCore.QRect(370, 140, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.p_quanly.setFont(font)
        self.p_quanly.setStyleSheet("QPushButton#p_quanly{\n"
"background-color: qlineargradient(spread:pad, x1:0.0199005, y1:0.204, x2:0.726, y2:0.7105, stop:0.19403 rgba(63, 183, 186, 255), stop:0.900498 rgba(115, 214, 139, 255));\n"
"border-radius: 15px;\n"
"}\n"
"QPushButton#p_quanly::hover{\n"
"    background-color:rgb(255, 170, 0);\n"
"}\n"
"")
        self.p_quanly.setObjectName("p_quanly")
        self.p_muonvatra = QtWidgets.QPushButton(self.frame)
        self.p_muonvatra.setGeometry(QtCore.QRect(210, 140, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.p_muonvatra.setFont(font)
        self.p_muonvatra.setStyleSheet("QPushButton#p_muonvatra{\n"
"background-color: qlineargradient(spread:pad, x1:0.0199005, y1:0.204, x2:0.726, y2:0.7105, stop:0.19403 rgba(63, 183, 186, 255), stop:0.900498 rgba(115, 214, 139, 255));\n"
"border-radius: 15px;\n"
"}\n"
"QPushButton#p_muonvatra::hover{\n"
"    background-color:rgb(255, 170, 0);\n"
"}\n"
"")
        self.p_muonvatra.setObjectName("p_muonvatra")
        self.p_thongke = QtWidgets.QPushButton(self.frame)
        self.p_thongke.setGeometry(QtCore.QRect(530, 140, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.p_thongke.setFont(font)
        self.p_thongke.setStyleSheet("QPushButton#p_thongke{\n"
"background-color: qlineargradient(spread:pad, x1:0.0199005, y1:0.204, x2:0.726, y2:0.7105, stop:0.19403 rgba(63, 183, 186, 255), stop:0.900498 rgba(115, 214, 139, 255));\n"
"border-radius: 15px;\n"
"}\n"
"QPushButton#p_thongke::hover{\n"
"    background-color:rgb(255, 170, 0);\n"
"}\n"
"\n"
"\n"
"")
        self.p_thongke.setObjectName("p_thongke")
        self.p_dx = QtWidgets.QPushButton(self.frame)
        self.p_dx.setGeometry(QtCore.QRect(680, 140, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.p_dx.setFont(font)
        self.p_dx.setStyleSheet("QPushButton#p_dx{\n"
"background-color: qlineargradient(spread:pad, x1:0.0199005, y1:0.204, x2:0.726, y2:0.7105, stop:0.19403 rgba(63, 183, 186, 255), stop:0.900498 rgba(115, 214, 139, 255));\n"
"border-radius: 15px;\n"
"}\n"
"QPushButton#p_dx::hover{\n"
"    background-color:rgb(255, 170, 0);\n"
"}\n"
"")
        self.p_dx.setObjectName("p_dx")
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setGeometry(QtCore.QRect(50, 20, 891, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color:rgb(255, 255, 255),\n"
"")
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setGeometry(QtCore.QRect(920, 40, 201, 161))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("Hinhanh/logo1.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.p_trangchu.raise_()
        self.p_quanly.raise_()
        self.p_muonvatra.raise_()
        self.p_thongke.raise_()
        self.p_dx.raise_()
        self.label_17.raise_()
        self.label_16.raise_()
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(110, 550, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(160, 950, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(460, 550, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(840, 540, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setGeometry(QtCore.QRect(780, 230, 231, 321))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap(":/hinhanh/Hinhanh/nguyenngocki.jpg"))
        self.label_14.setScaledContents(True)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setGeometry(QtCore.QRect(620, 940, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(30, 220, 291, 331))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/hinhanh/Hinhanh/dacnhantam.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(330, 230, 351, 311))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/hinhanh/Hinhanh/nha-gia-kim.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(570, 570, 241, 361))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/hinhanh/Hinhanh/python.webp"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(170, 590, 231, 351))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/hinhanh/Hinhanh/tuoitre.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        Trangchu.setCentralWidget(self.centralwidget)

        self.retranslateUi(Trangchu)
        QtCore.QMetaObject.connectSlotsByName(Trangchu)

    def retranslateUi(self, Trangchu):
        _translate = QtCore.QCoreApplication.translate
        Trangchu.setWindowTitle(_translate("Trangchu", "MainWindow"))
        self.p_trangchu.setText(_translate("Trangchu", "Trang chủ"))
        self.p_quanly.setText(_translate("Trangchu", "Quản lý sách"))
        self.p_muonvatra.setText(_translate("Trangchu", "Mượn và trả"))
        self.p_thongke.setText(_translate("Trangchu", "Thống kê"))
        self.p_dx.setText(_translate("Trangchu", "Đăng xuất"))
        self.label_16.setText(_translate("Trangchu", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">HỆ THỐNG THƯ VIỆN SÁCH ĐIỆN TỬ</span></p></body></html>"))
        self.label_8.setText(_translate("Trangchu", "ĐẮC NHÂN TÂM"))
        self.label_11.setText(_translate("Trangchu", "TUỔI TRẺ ĐÁNG GIÁ BAO NHIÊU ?"))
        self.label_12.setText(_translate("Trangchu", "NHÀ GIẢ KIM"))
        self.label_13.setText(_translate("Trangchu", "TÔI ĐI HỌC"))
        self.label_15.setText(_translate("Trangchu", "PYTHON CƠ BẢN"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Trangchu = QtWidgets.QMainWindow()
    ui = Ui_Trangchu()
    ui.setupUi(Trangchu)
    Trangchu.show()
    sys.exit(app.exec_())
